### ISSUE TITLE
Pickaxe doesn't work

### ISSUE THREAD

**Issue by tiendatbinhan** [MythrilBagels/Create-Alloyed#81] opened 2023-06-01 17:02 UTC
VERSIONS
Minecraft - 1.18.2
Create - 0.5.1.b
Flywheel - 0.6.8.a
Alloyed - 1.5a

DESCRIPTION
The pickaxe loses its functionality in Survival Mode. They cannot mine anything.

STEPS TO REPRODUCE
This is very easy to reproduce. Here are some ways to do it:
- Launch a world in Creative Mode, get any pickaxe, place a stone, and then switch back to Survival Mode via cheats. After that try to break the stone.
- Create a world in Survival Mode, get yourself a wooden pickaxe, then find any stone and try to break it.

**Comment by NightmareTwilight** [comment] 2023-06-02 16:02
Duplicate of #77 . The issue seems to be caused due to an error with the "minecraft:mineable/pickaxe" tag.

**Comment by tiendatbinhan** [comment] 2023-06-02 16:36
> Duplicate of #77 . The issue seems to be caused due to an error with the "minecraft:mineable/pickaxe" tag.

So, when will the hotfix of this be released?

**Comment by NightmareTwilight** [comment] 2023-06-02 19:54
> > Duplicate of #77 . The issue seems to be caused due to an error with the "minecraft:mineable/pickaxe" tag.
> 
> So, when will the hotfix of this be released?

No idea, not a dev, just noted what the error was since I had the same issue, and discovered the cause while looking through the debug log. It also affected axes. Basically, when one instance of the tag fails, Minecraft removes the tag all together, which isn’t just a mod issue, but a general one, which has been reported to Mojang. Until they fix it (basically by ignoring the one that failed), every single one needs to make sure that it doesn’t fail, otherwise everything breaks.

**Comment by tiendatbinhan** [comment] 2023-06-03 07:25
> > > Duplicate of #77 . The issue seems to be caused due to an error with the "minecraft:mineable/pickaxe" tag.
> > 
> > 
> > So, when will the hotfix of this be released?
> 
> No idea, not a dev, just noted what the error was since I had the same issue, and discovered the cause while looking through the debug log. It also affected axes. Basically, when one instance of the tag fails, Minecraft removes the tag all together, which isn’t just a mod issue, but a general one, which has been reported to Mojang. Until they fix it (basically by ignoring the one that failed), every single one needs to make sure that it doesn’t fail, otherwise everything breaks.

Ah, I've found a quick solution.
There's an inconsistency between pickaxe.json in the mod file and in this repository. The pickaxe.json in the mod file has two extra lines comparing to one in this repository. If remove these extra lines, the pickaxes and axes will work as usual.

**Comment by MrFastZombie** [comment] 2023-06-04 04:31
> Ah, I've found a quick solution. There's an inconsistency between pickaxe.json in the mod file and in this repository. The pickaxe.json in the mod file has two extra lines comparing to one in this repository. If remove these extra lines, the pickaxes and axes will work as usual.

I had to delete wooden_doors.json to get axes working, but it looks like it is not supposed to be there anyways. Deleting those lines in pickaxe.json only made picks work for me.

**Comment by FortressNebula** [comment] 2023-06-05 18:41
Fixed. Modfile has been taken down and the fixed version was uploaded.

**Closed as completed by FortressNebula** 2023-06-05 18:41 UTC

**Comment by FortressNebula** [comment] 2023-06-05 20:01
(Thanks to everyone for being helpful about the issue too, very much appreciated!)
