### ISSUE TITLE
Issue: Cobwebs don't turn into string

### ISSUE THREAD

**Issue by DragonGirl7567** [MythrilBagels/Create-Alloyed#9] opened 2022-02-05 21:58 UTC
**VERSIONS**
Minecraft - [1.18.1]
Create - [Create 1.18.1 v0.4d]
Flywheel - [flywheel-forge-1.18-0.6.0]
Alloyed - [alloyed-1.18.1-v0.1]

**DESCRIPTION**
cobwebs don't break and turn into string in water or when you use a sword.

**STEPS TO REPRODUCE**
install mod
open Minecraft
try to break web with water or a sword

**Comment by DragonGirl7567** [comment] 2022-02-05 21:59
(P.S. sorry that I didn't post it right)

**Comment by FortressNebula** [comment] 2022-02-05 22:30
Thanks for the issue, but I'm afraid I can't reproduce? When I place down cobwebs into water they break just fine. Are you using any other mods?

**Comment by DragonGirl7567** [comment] 2022-02-05 23:08
Maybe it is on my side, sorry to bother

**Comment by DragonGirl7567** [comment] 2022-02-05 23:49
tried updating forge to 39.066 and tried removing all mods except the create, flywheel and create: alloyed, and I get cobweb when I place in water

**Comment by FortressNebula** [comment] 2022-02-06 10:39
That's very strange, I'll look into that. It seems loot tables in general are a bit broken on the 1.18.

**Comment by FortressNebula** [comment] 2022-02-06 13:55
Yeah all loot tables in the 1.18 release are broken. We're working on fixing it.

**Comment by FortressNebula** [comment] 2022-02-07 21:28
Alright this issue is fixed and will be resolved in the next update. Thanks for bringing it to our attention!

**Closed as completed** 2022-02-07 21:37 UTC
Labels: bug, solved, serious
